# Chunking
SENTENCES_PER_CHUNK = 6

# Ranking
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# Summarization
SUMMARIZER_MODEL = "sshleifer/distilbart-cnn-12-6"
MIN_CHUNK_CHARS = 50
SUMMARY_MAX_LENGTH = 160
SUMMARY_MIN_LENGTH = 60
TOP_N_PER_SECTION = 4
NUM_BEAMS = 3
COMPRESSION_RATIO = 0.4

# Aggregation
AGGREGATE_MAX_LENGTH = 300
AGGREGATE_MIN_LENGTH = 40

# TLDR Summary
TLDR_MAX_LENGTH = 90
TLDR_MIN_LENGTH = 30
TLDR_SECTIONS = ("abstract", "introduction", "conclusion")