# Chunking
SENTENCES_PER_CHUNK = 6

# Ranking
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# Summarization
SUMMARIZER_MODEL = "facebook/bart-large-cnn"
MIN_CHUNK_CHARS = 50
SUMMARY_MAX_LENGTH = 250
SUMMARY_MIN_LENGTH = 30
TOP_N_PER_SECTION = 5

# Aggregation
AGGREGATE_MAX_LENGTH = 300
AGGREGATE_MIN_LENGTH = 40