# Chunking
SENTENCES_PER_CHUNK = 5

# Ranking
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# Summarization
SUMMARIZER_MODEL = "sshleifer/distilbart-cnn-12-6"
TOP_N_CHUNKS = 5
MIN_CHUNK_CHARS = 50
SUMMARY_MAX_LENGTH = 150
SUMMARY_MIN_LENGTH = 30
TOP_N_PER_SECTION = 2

# Aggregation
AGGREGATE_MAX_LENGTH = 300
AGGREGATE_MIN_LENGTH = 100